spin_manifest_version = 2

[application]
name = "arse"
version = "0.0.1"

[[trigger.http]]
route = "/..."
component = "my"

[component.my]
source = "test.wasm"
# build.command = "$CC test.cpp bindings/http_trigger.cpp bindings/http_trigger_component_type.o -mexec-model=reactor -o test.wasm"
# build.command = "../wasi-sdk-27.0-x86_64-linux/bin/wasm32-wasip2-clang++ --sysroot=../wasi-sdk-27.0-x86_64-linux/share/wasi-sysroot -I ../wasi-sdk-27.0-x86_64-linux/share/wasi-sysroot/include/wasm32-wasip2 -I ../wasi-sdk-27.0-x86_64-linux/share/wasi-sysroot/include/wasm32-wasip2/c++/v1 test.cpp bindings/http_trigger.cpp bindings/http_trigger_component_type.o -mexec-model=reactor -o test.wasm"
build.command = "../wasi-sdk-33.0-x86_64-linux/bin/clang++ -std=c++20 -I bindings -I expected -target wasm32-wasip2 test.cpp bindings/http_trigger.cpp bindings/http_trigger_component_type.o -mexec-model=reactor -o test.wasm"
