spin_manifest_version = 2

[application]
name = "cpp-test"
version = "0.0.1"

[[trigger.http]]
route = "/..."
component = "my"

[component.my]
source = "test.wasm"
build.command = "../wasi-sdk-33.0-x86_64-linux/bin/clang++ --sysroot=../wasi-sdk-33.0-x86_64-linux/share/wasi-sysroot -fno-exceptions -std=c++23 -I bindings -target wasm32-wasip2 test.cpp bindings/http_trigger.cpp bindings/http_trigger_component_type.o -mexec-model=reactor -o test.wasm"
